### ISSUE TITLE
[Feat] 쿠키와 세션 기능 추가

### ISSUE THREAD

**Issue by seokunee** [42webserv/42webserv#110]
## 📃 Description

- 쿠키와 세션에 대해서 공부를 하고 기능을 추가한다.

## ☑ Todo
- [x] 쿠키 구현
- [x] 세션 구현
- [x] 쿠키 만료기간 설정
- [x] 만료된 쿠키가 들어온 경우 만료되었는지 확인 - 필수 no - 세션 Id를 사용하는 부분이 없기 때문이다.
- [x] 쿠키 삭제하게 하는 기능 추가 - 필수 no - 세션 Id를 사용하는 부분이 없기 때문이다. -> 이 부분은 cgi에게 질문을 좀 해야할 것 같다.
왜나하면, 쿠키를 삭제하는 요청을 보내도록 하는건데 그걸 어떤 식으로 해줘야할지 모르겠다. 예를 들어서 지금은 session 요청을 /session path로 줬는데 쿠키를 삭제하려면 예를 들어 /session/delete 로 요청을 다시 누면 되는 것인지 이부분은 어디서 처리를 해줘야할지, 이벤트 부분에서 해도 상관없는지.
- [x] 만약 예전에 사용했던 쿠키가 딸려왔다면 어떻게 할 것인가. 그 쿠키는 만료되었다. 그래서 첫 요청에 바로 쿠키가 들어온다. => 그냥 바로 업데이트 시켜야겠다
