### ISSUE TITLE
[Event] 시그널 핸들링

### ISSUE THREAD

**Issue by get6** [42webserv/42webserv#13]
## 📃 Description
시그널 입력이 들어오는 경우 소켓을 종료할 필요가 있음.

## ☑ Todo
- [x] nginx 시그널 처리 방법 조사
- [x] 시그널 클래스 생성
- [x] 시그널 종류별 처리
