### ISSUE TITLE
[Feat] TESTER worker 쪽 해결하기

### ISSUE THREAD

**Issue by seokunee** [42webserv/42webserv#144]
## 📃 Description
TESTER worker 쪽 해결하기

## ☑ Todo
 - [x] Test multiple workers(5) doing multiple times(15): GET on /
 - [x] Test multiple workers(20) doing multiple times(5000): GET on /
 - [x] Test multiple workers(128) doing multiple times(50): GET on /directory/nop
 - [x] Test multiple workers(20) doing multiple times(5): Put on /put_test/multiple_same with size 1000000
