### ISSUE TITLE
서브젝트 확인 

### ISSUE THREAD

**Issue by seokunee** [42webserv/42webserv#146]
## 📃 Description

서브젝트 확인

## ☑ Todo
# 웹서브 pdf 체크 리스트

### Introduction

HTTP(Hypertext Transfer Protocol)는 분산협업하고, 하이퍼미디어 정보 시스템에서 사용되는 응용 프로토콜입니다. HTTP는 웹 데이터 통신의 기초이며, 사용자가 하이퍼링크를 클릭하거나 스크린을 탭하는 등의 방식으로 다른 리소스에 쉽게 접근할 수 있는 웹 페이지의 기반입니다. 이러한 목적으로 HTTP는 개발되었습니다.

웹 서버의 주요 기능은 클라이언트에게 웹 페이지를 저장, 처리 및 전달하는 것입니다. 클라이언트와 서버 간의 통신은 HTTP를 사용하여 이루어집니다. 전달되는 페이지는 대개 텍스트 내용 외에 이미지, 스타일 시트 및 스크립트를 포함한 HTML 문서입니다. 대형 웹사이트의 경우 다수의 웹 서버가 사용될 수 있습니다.

사용자 에이전트(일반적으로 웹 브라우저나 웹 크롤러)는 HTTP를 사용하여 특정 리소스를 요청함으로써 통신을 시작하고, 서버는 해당 리소스의 내용 또는 그것을 제공하지 못할 경우 오류 메시지로 응답합니다. 리소스는 일반적으로 서버의 보조 저장소에 있는 실제 파일이지만, 이는 웹 서버의 구현 방식에 따라 달라질 수 있습니다.

HTTP의 주요 기능은 콘텐츠 제공이지만, HTTP의 전체 구현은 클라이언트로부터 콘텐츠를 받는 방법도 포함합니다. 이 기능은 웹 폼을 제출하는 데 사용되며 파일 업로드도 가능합니다.

개념 설명:

- HTTP: 분산협업하고, 하이퍼미디어 정보 시스템에서 사용되는 응용 프로토콜입니다.
- 웹 서버: 클라이언트에게 웹 페이지를 저장, 처리 및 전달하는 기능을 수행합니다.
- HTML: 전달되는 페이지의 대부분은 HTML 문서로, 텍스트 내용 외에 이미지, 스타일 시트 및 스크립트를 포함합니다.
- 웹 브라우저/웹 크롤러: HTTP를 사용하여 서버로부터 리소스를 요청하고 받아오는 역할을 합니다.
- 웹 폼: HTTP를 사용하여 클라이언트로부터 콘텐츠를 받는 방법으로, 웹 폼을 제출하는 데 사용됩니다. 파일 업로드도 가능합니다.

### General rules

당신의 프로그램은 모든 상황에서 (메모리 부족 등) 크래시하지 않아야 하며 예기치 않게 종료되어서는 안 됩니다.
그렇게 되면 프로젝트는 기능이 없는 것으로 간주되며, 점수는 0점이 됩니다.
- [x] 소스 파일을 컴파일하는 Makefile을 제출해야 합니다. 다시 링크하면 안 됩니다.
- [x] Makefile은 반드시 $(NAME), all, clean, fclean 및 re 규칙을 포함해야 합니다.
- [x] 코드를 c++ 및 -Wall -Wextra -Werror 플래그로 컴파일해야 합니다.
- [x] 코드는 C++ 98 표준을 준수해야 합니다. 그러면 -std=c++98 플래그를 추가하면 여전히 컴파일됩니다.
- [x] 가능한 한 항상 최신 C++ 기능을 사용하세요 (예: <string.h>보다는 <cstring>을 선택하십시오). C 함수를 사용할 수 있지만 가능하면 항상 C++ 버전을 선호하세요.
- [x] 외부 라이브러리 및 Boost 라이브러리는 금지됩니다.

### Mandatory part

C++ 98로 HTTP 서버를 작성해야 합니다.
실행 파일은 다음과 같이 실행됩니다:
./webserv [구성 파일]

제목과 평가 척도에 poll()이 언급되어 있지만, select(), kqueue(), 또는 epoll()과 같은 동등한 기능을 사용할 수 있습니다.

프로젝트를 시작하기 전에 RFC를 읽고 telnet 및 NGINX를 사용하여 몇 가지 테스트를 수행해야 합니다.
RFC를 모두 구현할 필요는 없지만, 읽는 것은 필요한 기능을 개발하는 데 도움이 됩니다.

### Requirements

프로그램은 구성 파일을 인수로 받거나 기본 경로를 사용해야 합니다.
- [x] 다른 웹 서버를 execve 할 수 없습니다.
- [x] 서버는 절대 블로킹되면 안 되며, 클라이언트가 필요한 경우 적절하게 다루어져야 합니다.
- [x] 블로킹되지 않고, 모든 I/O 작업 (리스닝 포함)에 대해 1개의 poll() (또는 이와 동등한)만 사용해야 합니다.
- [x] poll() (또는 동등한)은 읽기와 쓰기를 동시에 확인해야 합니다.
- [x] 읽기 또는 쓰기 작업을 poll() (또는 동등한) 없이 수행해서는 안 됩니다.
- [x] read 또는 write 작업 후에 errno 값을 확인하는 것은 엄격히 금지됩니다.
- [x] 구성 파일을 읽기 전에는 poll() (또는 동등한)을 사용할 필요가 없습니다.

블로킹되지 않는 파일 디스크립터를 사용해야 하기 때문에,
read/recv 또는 write/send 함수를 사용할 수 있지만, poll() (또는 동등한)을 사용하지 않으면 서버가 블로킹될 수 있습니다.
그러므로, poll() (또는 동등한)을 사용하지 않고 파일 디스크립터의 읽기/수신 또는 쓰기/송신을 시도하면, 점수가 0점이 됩니다.

FD_SET, FD_CLR, FD_ISSET, FD_ZERO와 같은 모든 매크로와 정의를 사용할 수 있습니다. (그것들이 무엇을 하는지 이해하는 것이 매우 유용합니다.)
- [ ] 서버 요청은 영원히 멈춰서는 안 됩니다.
- [x] 서버는 사용자가 선택한 웹 브라우저와 호환되어야 합니다.
- [x] NGINX가 HTTP 1.1 호환성을 가지고 있고 헤더 및 응답 동작을 비교할 수 있다고 가정합니다.
- [x] HTTP 응답 상태 코드는 정확해야 합니다.
- [x] 기본 오류 페이지가 제공되지 않은 경우에도 서버가 있어야 합니다.
- [x] CGI 외에는 fork를 사용할 수 없습니다. (예: PHP, Python 등)
- [x] 정적 웹 사이트를 완전히 제공할 수 있어야 합니다.
- [x] 클라이언트는 파일 업로드를 할 수 있어야 합니다.
- [x] GET, POST, DELETE 방법이 최소한 있어야 합니다.
- [x] 서버를 스트레스 테스트해야 합니다. 비용이든 무엇이든 상관없이 항상 사용 가능해야 합니다.
- [x] 서버는 여러 port의 신호를 처리할 수 있어야 한다.

### For MacOS only

MacOS에서는 다른 유닉스 OS와는 다르게 write()를 구현하지 않으므로, fcntl()을 사용할 수 있습니다. 파일 디스크립터를 논블로킹 모드로 사용하여 다른 유닉스 OS와 비슷한 동작을 얻을 수 있습니다.

하지만, 다음과 같은 방식으로만 fcntl()을 사용할 수 있습니다.
fcntl(fd, F_SETFL, O_NONBLOCK);
다른 플래그는 허용되지 않습니다.

### Configuration file

 설정 파일에서는 다음과 같은 기능을 구현해야합니다
- [x] 각 서버의 포트와 호스트를 선택할 수 있습니다.
- [x] 서버 이름을 설정하거나 설정하지 않을 수 있습니다.
- [ ] 호스트:포트의 첫 번째 서버는 해당 호스트:포트의 기본값입니다. (즉, 다른 서버에 속하지 않는 모든 요청에 대해 응답합니다.)
- [x] 기본 오류 페이지를 설정할 수 있습니다.
- [x] 클라이언트 본문 크기를 제한할 수 있습니다.
- [x] 라우트를 다음 규칙/구성 중 하나 이상으로 설정할 수 있습니다 (라우트는 정규식을 사용하지 않습니다):
- [x] 라우트에 대한 수락된 HTTP 메소드 목록을 정의합니다.
- [ ] HTTP 리디렉션을 정의합니다.
- [x] 파일이나 디렉토리를 정의하여 해당 파일이나 디렉토리에서 검색하도록 설정합니다. (예: url /kapouet이 /tmp/www로 루트되면 url /kapouet/pouic/toto/pouet은 /tmp/www/pouic/toto/pouet입니다.)
- [ ] 디렉토리 목록을 켜거나 끌 수 있습니다.
- [ ] 디렉토리가 요청인 경우 응답할 기본 파일을 설정할 수 있습니다.
- [ ] 특정 파일 확장자를 기반으로 CGI를 실행할 수 있습니다 (예: .php).
- [x] POST 및 GET 메소드와 함께 작동하도록 할 수 있습니다.
- [ ] 라우트가 업로드된 파일을 수락하고 저장되는 위치를 구성할 수 있도록 합니다.
- [ ] CGI가 무엇인지 궁금한가요?
- [ ] 직접 CGI를 호출하지 않으므로 PATH_INFO를 전체 경로로 사용합니다.
- [x] 청크 요청의 경우 서버에서 청크를 해제해야하며 CGI는 본문의 끝으로 EOF를 기대합니다.
- [x] CGI에서 content_length가 반환되지 않으면 EOF가 반환된 데이터의 끝을 나타냅니다.
- [ ] 프로그램은 요청된 파일을 첫 번째 인수로 CGI를 호출해야합니다.
- [ ] CGI는 상대 경로 파일 액세스를 위해 올바른 디렉토리에서 실행되어야합니다.
- [ ] 서버는 하나의 CGI (php-CGI, Python 등)와 함께 작동해야합니다.
평가 중에는 모든 기능이 작동하는 것을 테스트하고 보여주기 위한 구성 파일 및 기본 파일을 제공해야합니다.v

만약 특정 동작에 대한 질문이 있다면, 자신의 프로그램 동작을 NGINX와 비교해 보아야 합니다. 예를 들어, server_name이 어떻게 동작하는지 확인해보세요. 작은 테스터를 제공해 드렸지만, 브라우저 및 테스트를 통해 모든 것이 원활하게 동작한다면 이를 통과할 필요는 없지만, 버그를 찾는 데 도움이 될 수 있습니다.

- [ ] 중요한 것은 내구성입니다. 서버는 절대로 멈추지 않아야 합니다.

하나의 프로그램으로만 테스트하지 마십시오. 좀 더 편리한 언어인 Python, Golang 등으로 테스트를 작성하십시오. C 또는 C++로도 작성할 수 있습니다.
