### ISSUE TITLE
[Refactor] 유틸 함수들 분리해 사용하기

### ISSUE THREAD

**Issue by chanwoong1** [42webserv/42webserv#153]
## 📃 Description

유틸 함수들 분리해서 사용하는 방안

## ☑ Todo
- [x] Utils 클래스 생성 및 HTTPRequestParser 코드 정리
- [x] ftToString 코드 이동 및 to_string 삭제
- [x] toHexString 함수 Utils 클래스에 추가
- [x] minPos 사용 부분 코드 리팩토링
- [x] StatusCodeMap 추가
- [x] generateErrorHeader 제거
- [x] generateHeader 함수 코드 변경
- [x] errorPageGenerator Utils에 추가
- [x] setTimer, deleteTimer 함수 Utils에 추가
- [x] getExpiryDate, ftStoi 함수 Utils에 추가
- [x] uploadPageGenerator함수 Utils에 추가
- [x] findDirectiveNameValue 함수 Utils에 추가
- [x] findDirective 함수 Utils에 추가
- [x] getContentType, lower, isEqual 함수 Utils에 추가
- [x] readFile, writeFile 함수 Utils에 추가
- [x] isDirectory, isFile, isMethod 함수 Utils에 추가
- [x] commonProcess -> Utils
- [x] 기존과 동작이 동일한지 확인
