### ISSUE TITLE
[Fix] 파싱단에서 잘못된 요청이 오는 경우 400 처리

### ISSUE THREAD

**Issue by get6** [42webserv/42webserv#160]
## 📃 Description
tester는 잘못된 요청을 여러번 주지만, 아예 잘못된 요청이 오는 경우에 대한 처리가 불분명합니다.
curl이나 telnet을 통해 RFC에 위배되는 문자열이 들어오면 Bad Request 응답을 보내야 하는 처리를 살펴야 합니다.

[HTTP 헤더](https://developer.mozilla.org/ko/docs/Web/HTTP/Headers)를 살펴보고 추가적으로 작업해야 할 것들도 Todo에 적어서 작업할 예정입니다.

## ☑ Todo
- [ ] 파싱단에서 Bad Request 응답할 수 있도록 함수 생성
파싱 이후에는 Request를 만들면서 헤더와 바디를 검사한 뒤 올바르면 Response 생성으로 빠지고 에러가 있다면 Bad Request를 던져야 합니다.
- [x] 테스터 대신 잘못된 요청 보내보기
단순히 파싱이 안된다고 잘못된 요청을 보내면 테스터기는 Bad status code로 종료됩니다.
- [ ] #157
- [ ] 상황별로 다시 읽을지, 응답할지 처리할 로직 구상
파싱이 완료되기 전까지는 계속 읽기로 시도합니다. 타임아웃으로 특정 시간까지 오지 않는다면 Bad Request를 던져 연결을 종료합니다.
- [x] kqueue에 timeout 설정하기
