### ISSUE TITLE
[Parsing] DefaultConfig 클래스 기본 지시문 처리

### ISSUE THREAD

**Issue by get6** [42webserv/42webserv#19]
## 📃 Description
[Core functionality](http://nginx.org/en/docs/ngx_core_module.html) 페이지에 기본값 설정을 볼 수 있음.
nginx.conf 파일에 설정이 없다면 기본 설정이 들어갈 것 같음. 이를 토대로 작업

## ☑ Todo
- [x] 주요 설정 확인하기 

# 주로 쓰는 설정들

## main
```bash
Syntax: worker_processes number | auto;
Default: worker_processes 1;
Context: main

Syntax: http { ... }
Default: -
Context: main
```

## common
여기에 http, server, location에 같이 쓰는게 많아서 몰아넣음~
```bash
Syntax: location [ = | ~ | ~* | ^~ ] uri { ... }
        location @name { ... }
Default: -
Context: server, location (주로 location)

Syntax: root path;
Default: root html;
Context: http, server, location, if in location (주로 location)

Syntax: index file ...;
Default: index index.html;
Context: http, server, location (주로 location)

Syntax: error_page code ... [=[response]] uri;
Default: -
Context: http, server, location, if in location (주로 server)

Syntax: include file | mask;
Default: -
Context: any (주로 http)

Syntax: default_type mime-type;
Default: default_type text/plain;
Context: http, server, location (주로 http)

Syntax: keepalive_timeout timeout [header_timeout];
Default: keepalive_timeout 75s;
Context: http, server, location (주로 http)
```

## http
```bash
Syntax: server { ... }
Default: -
Context: http
```

## server
```bash
Syntax: listen address[:port] [default_server] [ssl] [http2 | quic | spdy] [proxy_protocol] [setfib=number] [fastopen=number] [backlog=number] [rcvbuf=size] [sndbuf=size] [accept_filter=filter] [deferred] [bind] [ipv6only=on|off] [reuseport] [so_keepalive=on|off|[keepidle]:[keepintvl]:[keepcnt]];
        listen port [default_server] [ssl] [http2 | quic | spdy] [proxy_protocol] [setfib=number] [fastopen=number] [backlog=number] [rcvbuf=size] [sndbuf=size] [accept_filter=filter] [deferred] [bind] [ipv6only=on|off] [reuseport] [so_keepalive=on|off|[keepidle]:[keepintvl]:[keepcnt]];
        listen unix:path [default_server] [ssl] [http2 | quic | spdy] [proxy_protocol] [backlog=number] [rcvbuf=size] [sndbuf=size] [accept_filter=filter] [deferred] [bind] [so_keepalive=on|off|[keepidle]:[keepintvl]:[keepcnt]];
Default: listen *:80 | *:8000;
Context: server

Syntax: server_name name ...;
Default: server_name "";
Context: server
```

- [x] Config에 없는 기본 설정은 DefaultConfig를 통해 넣어주기
   - 특정 블록 지시자가 생긴 경우 필수 지시자가 있는지 확인하기

- [x] Config 없이 DefaultConfig만 생성되는 경우 테스트 해보기 -> Config를 확인하는 유효성에 걸림
