### ISSUE TITLE
[Feature] Directive 구조체에서 원하는 Config 설정 값 찾기 및 가져오기

### ISSUE THREAD

**Issue by seokunee** [42webserv/42webserv#22]
## 📃 Description

Directive 구조체에서 원하는 Config 설정 값 찾기 및 가져오기
기본 값 세팅해주기

## ☑ Todo
- [x] server에 따른 location path 찾아주기
- [x] config 부모 자식 관계 에러 처리
- [x] include 파일 있는 경우 http 지시자와 같은 위치에 추가
- [x] main 지시자 감싸도록 처리
