### ISSUE TITLE
[Feature] 서버가 1개일 때를 가정해 Server와 Worker 클래스 연결

### ISSUE THREAD

**Issue by chanwoong1** [42webserv/42webserv#41]
## 📃 Description

Worker 클래스에 Server 클래스 추가 후 response까지 Server 클래스를 사용할 수 있도록 구현

## ☑ Todo
- [x] Worker 클래스에 Server 클래스 추가
- [x] HTTPResponse에 있는 함수들 Worker 클래스에 추가
- [x] #42
- [x] 기존 8080 포트번호를 Server의 저장된 포트번호로 교체
- [x] 기존 동작과 동일하게 동작하는지 확인
