### ISSUE TITLE
[Refactor] 다중 소켓 관리를 위한 클래스 구조 변경

### ISSUE THREAD

**Issue by chanwoong1** [42webserv/42webserv#42]
## 📃 Description

현재는 하나의 포트번호만 사용하고있는데, 다중 소켓을 사용할 경우, 구조 변경이 필요해보입니다.
따라서 Master, Socket, Worker의 구조를 변경해보고자 합니다.
또한, 소켓을 벡터로 관리하려합니다.

## ☑ Todo
- [x] Master 구조 변경
- [x] Socket 구조 변경
- [x] Worker 구조 변경
