### ISSUE TITLE
[CGI] 환경변수 세팅

### ISSUE THREAD

**Issue by Y2IN** [42webserv/42webserv#45]
## 📃 Description
 QUERY_STRING
 REMOTE_ADDR -> ip주소
 SCRIPT_NAME -> Uri
 SERVER_NAME 요청을 수신한 서버의 호스트 이름.
 SERVER_PORT 요청을 수신한 서버의 포트 번호

## ☑ Todo
- [x] QUERY_STRING
- [x] REMOTE_ADDR -> ip주소
- [x] SCRIPT_NAME -> Uri
- [ ] SERVER_NAME 요청을 수신한 서버의 호스트 이름.
- [x] SERVER_PORT 요청을 수신한 서버의 포트 번호
