### ISSUE TITLE
[Feature] 서버 별 고유한 포트번호를 사용할수 있도록 검증 기능 구현

### ISSUE THREAD

**Issue by chanwoong1** [42webserv/42webserv#49]
## 📃 Description
포트번호를 검증하자

## ☑ Todo
- [x] setUpListen 함수 내부에서 포트번호 중복 검사를 수행하는 코드 구현
- [x] 중복이 발견될 경우 에러 반환
- [x] 메모리 누수 체크
