### ISSUE TITLE
[Feature] getResource 함수 내부 root 경로 올바르게 연결

### ISSUE THREAD

**Issue by chanwoong1** [42webserv/42webserv#60]
## 📃 Description

포트번호를 통해 몇 번째 서버인지 확인했으므로 서버 블록에 적혀있는 root를 활용할 수 있음

## ☑ Todo
- [x] getResource 함수 내부 root 경로 올바르게 연결
- [x] 이전과 동일하게 동작하는지 확인
- [x] Server 클래스 index 지시자 처리 기능 추가
- [x] getResponse root 코드 리팩토링
