### ISSUE TITLE
[Feature] config file 에러 처리

### ISSUE THREAD

**Issue by seokunee** [42webserv/42webserv#64]
## 📃 Description
config file 에러 처리 추가

## ☑ Todo
- [x]  필요한 키가 있는지 확인 -> 선황이형이 하는 부분이랑 겹칠 것 같아서 형한테 물어보기 -> 선황이형이 처리
- [x]  불필요한 키가 있는지 확인
- pfd에 config file 내용에 의해서 index는 location에만 존재할 수 있도록 함.-> 수정 : http, server, location에서 다 가질 수 있는 지시자.
- client_max_body_size 지시자는 NGINX의 http, server, 또는 location 블록 중 하나에 사용할 수 있는데 우리는 곳에서 할지...생각해야할 것 같다. http에도 있고 server에도 있다면 둘 다 허락은 해주되, server의 client_max_body_size를 사용하는게 맞다는 생각이 들어서 일단은 다 허락을 해놓겠다.
- redirect -> return으로 바꾸었다. redirect은 아파치에서 사용하는 지시자인 것 같다. 그래서 return으로 대체함.
- cgi_info 지시자는 cgi 팀에게 필요한 것인가?
- [x]  key의 중복을 확인 
- [x]  각 vallue가 유효 형식/값/범위에 있는지 확인 
- error_page같은 경우는
error_page 403 /error_pages/403.html;
error_page 403 404  /error_pages/error.html;
이런 형식으로만 하도록 하였다.
- location의 path(=value)는 http 응답쪽에서 처리해주는 걸로 생각하고 따로 처리를 안했습니다.

- client_max_body_size는 숫자만 된다. 10m, 10k, 10g 이런거 안된다...

- [x]  error_page가 존재하는지 ->  권한이 있는지는 사용하는 측에서 하는 걸로 못읽으면 default error page를 해주는 식으로 하면 될 것 같다.
