### ISSUE TITLE
[Feature] 요청의 path이 서버의 location에 포함되어있을 경우 처리

### ISSUE THREAD

**Issue by chanwoong1** [42webserv/42webserv#66]
## 📃 Description

서버의 locaiton 목록에서 요청 path가 존재한다면 해당 location 블럭을 찾아 블럭안의 지시자들을 받아준 뒤 처리해준다.

```
root: 위치에 대한 문서 루트 디렉토리를 설정합니다.
index: 특정 파일이 요청되지 않은 경우 제공될 기본 파일을 지정합니다.
try_files: 요청을 제공하기 전에 파일이 존재하는지 확인해야 하는 순서를 정의합니다.
rewrite: URL을 수정하거나 요청을 다른 위치로 리디렉션할 수 있습니다.
access_log 및 error_log: 해당 위치에 대한 액세스 및 오류 로그를 기록하기 위한 로그 파일을 지정합니다.
limit_except: 위치에 대해 허용되는 HTTP 메서드를 제한합니다.
```

responseData가 다음과 같은 형식이고,
```
responseData {
	int clientFd = 8080;
	std::ifstream resourceFile;
	std::string root = ./asset;
	std::string index = index.htm;
	std::string resourcePath = ...;
	std::string contentType = ...;
}
```

path : /index 일 경우,

location 블록 중
```
location /index {
  index index.html
  root ./html
  limit_except GET POST DELETE
}
```
이면, 기존 responseData 구조체에 담긴 정보를 변경시켜준다.

변경 후 
```
responseData {
	int clientFd = 8080;
	std::ifstream resourceFile;
	std::string root = ./html;
	std::string index = index.html;
	std::string resourcePath = ...;
	std::string contentType = ...;
}
```

## ☑ Todo
- [x] path와 location의 값 확인 후 적절한 location을 찾아준 뒤 기존 Response 구조체 세팅과 병합
- [x] 이전과 동작이 동일한지 확인
- [x] limit_except가 server 블록에 존재하고 location에 존재하지 않는 경우 예외 발생 처리
