### ISSUE TITLE
[Event] 다중 소켓 포트 충돌 처리

### ISSUE THREAD

**Issue by get6** [42webserv/42webserv#75]
## 📃 Description
server 블록들에서 server_name과 port가 일치하는 경우가 생겨서 충돌이 날 때, 어떻게 처리해야 하면 좋을지 논의가 필요함.
우리끼리 먼저 생각을 얘기해보고 nginx는 어떻게 처리하는지 확인하고 테스트가 필요함
과제를 먼저 끝낸 사람들은 어떻게 처리했을지 얘기해보기.

## ☑ Todo
- [x] server_name과 port 지시문이 충돌나는 상황 발생시키기
- [x] 두개 이상의 server 블록으로 해당 케이스 테스트 하기
- [x] 파싱단에서 막아야 하나?
