### ISSUE TITLE
[Refactor] Worker 클래스 리팩토링

### ISSUE THREAD

**Issue by chanwoong1** [42webserv/42webserv#81]
## 📃 Description
Worker의 코드가 증가함에 따라 리팩토링이 필요해보입니다.

리팩토링을 할 때, response 부분을 클래스로 따로 정의해줘도 괜찮다 생각되어 새로운 클래스를 생성해도 좋아보입니다.

## ☑ Todo
- [x] #87
- [x] run 메서드 기능분리
- [x] response 부분 리팩토링
- [x] 기존과 같은 동작을 수행하는지 확인
