### ISSUE TITLE
[Feature] POST 처리

### ISSUE THREAD

**Issue by chanwoong1** [42webserv/42webserv#82]
## 📃 Description

POST 응답하는 코드 작성

## ☑ Todo
- [x] CGI POST 응답 처리
- [x] sanghan이가 postResponse 함수 만듦
- [x] sunhwang이 POST 테스터 케이스 확인 후 수정사항 반영하기

GET - 가져오는 느낌
POST - 수행하는 느낌

GET 방식으로 데이터를 보내기
URL 뒤에 붙여서 보냄
	예를 들어 아이디 패스워드를 보낸다고 한다면
	www.example.com?id=sanghan&pass=4242
	이런식으로 URL뒤에 '?' 마크를 통해 URL의 끝을 알리면서 데이터 표현의 시작점을 알림
	? 뒷 부분을 query string 이라고 하며 key=value와 같은 pair 형식
	& 연산자를 사용하여 여러개의 key와 value 값을 전달할 수도 있음
	URL에 붙이기 때문에, HTTP 패킷의 헤더에 포함되어 서버에 요청
	따라서 GET 방식에서 BODY에 특별한 내용을 넣을 것이 없으므로 BODY는 빈상태로 보내지고, 헤더의 내용중 BODY 데이터를 설명하는 Content-Type이라는 헤더필드는 들어가지 않음

POST방식으로 데이터를 보내기
BODY에다가 데이터를 넣어서 보냄
	헤더필드 중 BODY의 데이터를 설명하는 Content_Type이라는 헤더 필드가 들어가고 어떤 데이터 타입인지 명시함
	컨텐트 타입으로는 여러가지가 있는데 다음과 같은 예시가 있다
	1) application/x-www-form-urlencoded - 이 방식은 GET 방식과 비슷하게 key와 value 쌍으로 데이터를 넣고 똑같이 구분자 &를 쓴다.
	2)  text/plain - BODY에 단순  txt를 넣는다.
	3) multipart/form-data - 파일전송을 할 때 많이 쓰는데 BODY의 데이터를 바이너리 데이터로 넣는다는 것을 알려준다.

post
우리 과제에서는 txt파일에 body에 넣을 내용을 작성해두고 그 내용을 wirte 하는 방식으로

POST (append), PUT (**truncate**)
- 클라이언트 바디 사이즈 확인, 넘으면 413
- 허용된 업로드 Location확인, 아니면 403
- 해당 요청이 유효한 directory일 때
  -> config에 index자체가 없다면 500
  -> config에 index가 있는데, indexpage를 app(OR)trunc (없으면 생성(201), 있으면 새파일로(200))
- 해당 요청이 유효한 파일이면 app(OR)trunc  (200)
- 해당 요청이 없는 리소스일 때 (ex. /a/b/c)
  -> "/"로 끝나면 directory 요청이라고 간주하고 500
  -> 그렇지 않다면 파일이라고 간주함
     -> 그 중에 상위 디렉터리가 있다면 만들어주고 201 (ex. /a/b/가 있다면)
     -> 상위 디렉터리도 없다면 404
