### ISSUE TITLE
[Feature] autoindex에 연결할 html파일 생성 및 responseData 구조체 변경

### ISSUE THREAD

**Issue by 42kko** [42webserv/42webserv#84]
## 📃 Description
autoindex가 켜질경우 path 안에있는 모든 파일을들을 보여주는 html페이지를 동적으로 생성해서 응답해줌
responseData 안에 cgi에서 필요한 자료들을 cgi 클래스를 만들어 넣어줌
autoindex 하기전 location찾는 순서변경

## ☑ Todo
- [x] autoindex 켜짐 유무체크
- [x] autoindex에 연결해줄 동적 html파일
- [x] responseData 안에 cgi구조체 추가
- [x] #88
