### ISSUE TITLE
[Fix] develop 브랜치에서 발생하는 오류 수정

### ISSUE THREAD

**Issue by chanwoong1** [42webserv/42webserv#94]
## 📃 Description

develop 브랜치에서 발생하는 오류를 처리하는 브랜치입니다. 프로젝트 종료까지 상시 유지 해둘 예정입니다.

## ☑ Todo
- [X] 경로 설정 오류 수정
- [x] 프로그램 실행 시 segfault 발생하는 이슈 수정
- [X] ResponseData 생성 이후 request 구조체는 사용하지 않는 방향으로 수정
- [x] mime.types 실행하는 부분 response 클래스에서 처리
- [x] #67 
- [x] #154
