### ISSUE TITLE
[Config] DefaultConfig 함수 실행 위치를 Master -> Config로 변경

### ISSUE THREAD

**Issue by get6** [42webserv/42webserv#97]
## 📃 Description
DefaultConfig 위치 변경

## ☑ Todo
- [x] develop 브랜치에서 간단하게 위치만 변경
- [x] include 정렬 변경
- [x] getDirectives 함수의 반환값을 const reference로 변경
