### ISSUE TITLE
[Test] Tester 실행 후 오류사항 수정

### ISSUE THREAD

**Issue by chanwoong1** [42webserv/42webserv#99]
## 📃 Description

tester를 돌려봅시다.

tester는 이제 tester.conf로만 실행하기를 귄장합니다. 미리 테스터 환경에 맞춘 conf파일을 제작해 대비할 수 있도록 하는것이 좋을듯합니다.

실행 방법

```
// 터미널 두개 열고

// 터미널 1 실행
./webserv assets/conf/tester.conf

// 터미널 2 실행
./tester http://localhost:8080
```

## 참고 사항

GET 테스트 중 간혹 FATAL ERROR ON LAST TEST: read tcp 127.0.0.1:50417->127.0.0.1:8080: read: connection reset by peer 이 에러가 나면서 테스트가 종료되는 상황이 발생합니다. 어떻게 고쳐야할지 생각해봅시다.

## ☑ Todo
- [x] #104
- [x] 테스터 실행을 위한 tester.conf 제작
- [x] Test GET http://localhost:1234/
- [x] Test POST http://localhost:1234/ with a size of 0
- [x] Test HEAD http://localhost:1234/
    - HEAD에서 헤더 없이 요청이 올 수 있어서 추가 구현
    - 또한, 웹 서버가 요청보다 더 빠르게 클라이언트를 종료하는 현상 발생, sleep(1)을 주어 대기시간 확보
- [x] Test GET http://localhost:1234/directory
    - directory 로케이션 생성
- [x] Test GET http://localhost:1234/directory/youpi.bad_extension
- [x] Test GET http://localhost:1234/directory/youpi.bla
- [x] Test GET Expected 404 on http://localhost:1234/directory/oulalala
    - path를 줄여 location을 찾는 로직 제거
- [x] Test GET http://localhost:1234/directory/nop
    - /directory/nop location 추가
- [x] Test GET http://localhost:1234/directory/nop/
    - HTTPRequestParser에서 path 부분 마지막 "/" 제거하는 로직 추가
    - 단, location이 "/"일 경우에는 해당하지 않음
- [x] Test GET http://localhost:1234/directory/nop/other.pouic
- [x] Test GET Expected 404 on http://localhost:1234/directory/nop/other.pouac
- [x] Test GET Expected 404 on http://localhost:1234/directory/Yeah
- [x] Test GET http://localhost:1234/directory/Yeah/not_happy.bad_extension
- [x] Test Put http://localhost:1234/put_test/file_should_exist_after with a size of 1000
- [x] Test Put http://localhost:1234/put_test/file_should_exist_after with a size of 10000000
- [x] #116
- [x] #126
- [x] Test POST http://localhost:1234/directory/youpla.bla with a size of 100000000
- [x] #140
- [x] Test POST http://localhost:1234/directory/youpi.bla with a size of 100000 with special headers
- [x] Test POST http://localhost:1234/post_body with a size of 0
- [x] Test POST http://localhost:1234/post_body with a size of 100
- [x] Test POST http://localhost:1234/post_body with a size of 200
- [x] Test POST http://localhost:1234/post_body with a size of 101
- [x] Test multiple workers(5) doing multiple times(15): GET on /
- [x] Test multiple workers(20) doing multiple times(5000): GET on /
- [x] Test multiple workers(128) doing multiple times(50): GET on /directory/nop
- [x] Test multiple workers(20) doing multiple times(5): Put on /put_test/multiple_same with size 1000000
- [x] cgi-tester
